coverage:
  range: 70..100
  round: nearest
  precision: 2

ignore:
  - "**/examples/cpp" # ignore folders and all its contents
  - "/src/tracer"     # ignore folders and all its contents
  - "**/*.spec"       # glob accepted

comment: false
