#!/bin/bash

PIN_BIN_PATH=/home/jonathan/Works/Tools/pin-2.14-71313-gcc.4.4.7-linux/source/tools/Triton/../../../pin.sh
TRITON_LIB_PATH=/home/jonathan/Works/Tools/pin-2.14-71313-gcc.4.4.7-linux/source/tools/Triton/build/libtriton.so

if [ -z "$1" ]
  then
    echo "You need to specify a script"
    echo "Syntax: ./triton <your_script.py> <target pid>"
    exit
fi

if [ -z "$2" ]
  then
    echo "You need to specify a target binary"
    echo "Syntax: ./triton <your_script.py> <target pid>"
    exit
fi

$PIN_BIN_PATH -pid $2 -t $TRITON_LIB_PATH -script $1

